# Generated by Django 5.2.1 on 2025-11-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="min_cart_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum cart total required to apply this coupon.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="companysettings",
            name="payment_terms_days",
            field=models.PositiveIntegerField(blank=True, default=7, null=True, verbose_name="Payment terms (days)"),
        ),
    ]
