# Generated by Django 5.2.1 on 2025-11-17 07:14

import django.core.validators
import feedbacks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                ("sanitized_comment", models.TextField(blank=True, default="")),
                ("is_public", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("edited", "Edited"),
                            ("locked", "Locked"),
                            ("deleted", "Deleted"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("edit_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("internal_flag", models.BooleanField(default=False)),
                ("pinned", models.BooleanField(default=False)),
                ("staff_reply", models.TextField(blank=True, default="")),
                ("moderation_note", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeedbackAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to=feedbacks.models._feedback_attachment_path)),
                ("filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("file_size", models.PositiveIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="FeedbackAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("locked", "Locked"),
                            ("pinned", "Pinned"),
                            ("reply", "Staff Reply"),
                            ("moderated", "Moderated"),
                            ("attachment_added", "Attachment Added"),
                            ("attachment_deleted", "Attachment Deleted"),
                        ],
                        max_length=64,
                    ),
                ),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeedbackReminderLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("reminder_count", models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
    ]
