# Generated by Django 5.2.1 on 2025-11-17 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("feedbacks", "0001_initial"),
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedbacks_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="feedbacks", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="installation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="feedback", to="main.installationactivity"
            ),
        ),
        migrations.AddField(
            model_name="feedbackattachment",
            name="feedback",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="feedbacks.feedback"
            ),
        ),
        migrations.AddField(
            model_name="feedbackattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedback_attachments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feedbackauditlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedback_audit_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feedbackauditlog",
            name="feedback",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="audit_logs", to="feedbacks.feedback"
            ),
        ),
        migrations.AddField(
            model_name="feedbackreminderlog",
            name="installation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_reminder",
                to="main.installationactivity",
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(fields=["installation", "customer"], name="feedbacks_f_install_61c05f_idx"),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(fields=["status"], name="feedbacks_f_status_860cc7_idx"),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(fields=["created_at"], name="feedbacks_f_created_3a98a8_idx"),
        ),
    ]
