# Generated by Django 5.2.1 on 2025-11-17 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraCharge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "cost_type",
                    models.CharField(
                        choices=[
                            ("equipment", "Additional Equipment"),
                            ("cable", "Extra Cables"),
                            ("extender", "Signal Extender"),
                            ("router", "Router/Gateway"),
                            ("mounting", "Specialized Mounting"),
                            ("labor", "Additional Labor"),
                            ("power", "Power Infrastructure"),
                            ("access", "Access Infrastructure"),
                            ("safety", "Safety Equipment"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("item_name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("unit_price", models.DecimalField(decimal_places=2, help_text="Fixed price per unit", max_digits=10)),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether this item is available for selection"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, help_text="Order in which items appear in selection lists"),
                ),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                (
                    "specifications",
                    models.JSONField(blank=True, help_text="Additional technical specifications", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Extra Charge",
                "verbose_name_plural": "Extra Charges",
                "ordering": ["cost_type", "display_order", "item_name"],
            },
        ),
        migrations.CreateModel(
            name="SiteSurveyChecklist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("location", "Location & Access"),
                            ("signal", "Signal Quality"),
                            ("mounting", "Mounting Options"),
                            ("safety", "Safety Considerations"),
                            ("technical", "Technical Requirements"),
                            ("environmental", "Environmental Factors"),
                        ],
                        max_length=20,
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("yes_no", "Yes/No"),
                            ("text", "Text Response"),
                            ("multiple_choice", "Multiple Choice"),
                            ("rating", "Rating (1-5)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("choices", models.JSONField(blank=True, help_text="For multiple choice questions", null=True)),
                ("is_required", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["category", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="SiteSurvey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("requires_approval", "Requires Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("survey_latitude", models.FloatField(blank=True, null=True)),
                ("survey_longitude", models.FloatField(blank=True, null=True)),
                ("survey_address", models.TextField(blank=True)),
                ("location_notes", models.TextField(blank=True)),
                ("overall_assessment", models.TextField(blank=True, help_text="Technician's overall assessment")),
                ("installation_feasible", models.BooleanField(blank=True, null=True)),
                ("recommended_mounting", models.CharField(blank=True, max_length=100)),
                (
                    "requires_additional_equipment",
                    models.BooleanField(
                        blank=True, help_text="Whether additional equipment/costs are needed", null=True
                    ),
                ),
                (
                    "estimated_additional_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated total for additional costs",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "cost_justification",
                    models.TextField(blank=True, help_text="Detailed justification for additional costs"),
                ),
                (
                    "additional_costs_approved",
                    models.BooleanField(blank=True, help_text="Whether customer approved additional costs", null=True),
                ),
                ("submitted_for_approval_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approval_notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_surveys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_surveys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="site_survey", to="main.order"
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_surveys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdditionalBilling",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("billing_reference", models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ("tax_amount", models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ("total_amount", models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Customer Approval"),
                            ("approved", "Approved by Customer"),
                            ("rejected", "Rejected by Customer"),
                            ("processing", "Payment Processing"),
                            ("pending_verification", "Pending Payment Verification"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_for_approval_at", models.DateTimeField(blank=True, null=True)),
                ("customer_responded_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("customer_notes", models.TextField(blank=True, help_text="Customer's feedback or rejection reason")),
                ("admin_notes", models.TextField(blank=True, help_text="Admin notes for internal use")),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("payment_proof", models.FileField(blank=True, null=True, upload_to="additional_billing_payments/")),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, help_text="When this billing proposal expires", null=True),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_billings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="additional_billings", to="main.order"
                    ),
                ),
                (
                    "survey",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_billing",
                        to="site_survey.sitesurvey",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSurveyPhoto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("photo", models.ImageField(upload_to="site_survey_photos/")),
                (
                    "photo_type",
                    models.CharField(
                        choices=[
                            ("site_overview", "Site Overview"),
                            ("proposed_mounting", "Proposed Mounting Location"),
                            ("obstructions", "Obstructions"),
                            ("access_path", "Access Path"),
                            ("power_source", "Power Source"),
                            ("safety_concern", "Safety Concern"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="photos", to="site_survey.sitesurvey"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveyAdditionalCost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        help_text="Price automatically set from ExtraCharge",
                        max_digits=10,
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                (
                    "is_required",
                    models.BooleanField(default=True, help_text="Whether this item is absolutely necessary"),
                ),
                ("justification", models.TextField(help_text="Technician's justification for this additional cost")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "extra_charge",
                    models.ForeignKey(
                        blank=True,
                        help_text="Predefined equipment/service from the catalog",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="site_survey.extracharge",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_costs",
                        to="site_survey.sitesurvey",
                    ),
                ),
            ],
            options={
                "verbose_name": "Survey Additional Cost",
                "verbose_name_plural": "Survey Additional Costs",
                "ordering": ["extra_charge__cost_type", "extra_charge__item_name"],
            },
        ),
        migrations.CreateModel(
            name="SiteSurveyResponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("response_text", models.TextField(blank=True)),
                (
                    "response_rating",
                    models.PositiveIntegerField(blank=True, help_text="For rating questions (1-5)", null=True),
                ),
                (
                    "response_choice",
                    models.CharField(blank=True, help_text="For multiple choice questions", max_length=100),
                ),
                ("additional_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checklist_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="site_survey.sitesurveychecklist"
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="site_survey.sitesurvey",
                    ),
                ),
            ],
            options={
                "unique_together": {("survey", "checklist_item")},
            },
        ),
    ]
