"""
Django settings for nexus_backend project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import ctypes
import ctypes.util
import glob
import os
import ssl
from os.path import exists, isdir, join
from pathlib import Path

import certifi
from environ import Env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# initialized environ
env = Env()
env.read_env(os.path.join(BASE_DIR, ".env"))


def env_int_safe(key: str, default: int) -> int:
    raw = os.environ.get(key)  # read raw to distinguish empty string
    if raw is None:
        return default
    raw = str(raw).strip()
    if not raw:
        return default
    try:
        return int(raw)
    except ValueError:
        return default


def env_str_safe(key: str, default: str = "") -> str:
    raw = os.environ.get(key)
    return default if raw is None or str(raw).strip() == "" else str(raw).strip()


def env_bool_safe(key: str, default: bool) -> bool:
    raw = os.environ.get(key)
    if raw is None:
        return default
    s = str(raw).strip().lower()
    if s == "":
        return default
    return s in {"1", "true", "yes", "on"}


DEVELOPMENT_MODE = env.bool("DEVELOPMENT_MODE", default=True)

EMAIL_SSL_CONTEXT = ssl.create_default_context(cafile=certifi.where())

# Email backend selection
# Prefer Microsoft Graph via Anymail when available; fall back to SMTP.
import importlib.util as _importlib_util

# Visible sender (shared mailbox)
DEFAULT_FROM_EMAIL = "no-reply@nexus.cd"

# Gather MS365 credentials (support either MS365_* or O365_* env names)
MS365_CLIENT_ID = os.getenv("MS365_CLIENT_ID") or os.getenv("O365_CLIENT_ID")
MS365_TENANT_ID = os.getenv("MS365_TENANT_ID") or os.getenv("O365_TENANT_ID")
MS365_CLIENT_SECRET = os.getenv("MS365_CLIENT_SECRET") or os.getenv(
    "O365_CLIENT_SECRET"
)

try:
    _has_anymail_graph = (
        _importlib_util.find_spec("anymail.backends.microsoft_graph") is not None
    )
except Exception:
    # Be resilient when optional dependency is not installed
    _has_anymail_graph = False

if _has_anymail_graph and MS365_CLIENT_ID and MS365_TENANT_ID and MS365_CLIENT_SECRET:
    EMAIL_BACKEND = "anymail.backends.microsoft_graph.EmailBackend"
    ANYMAIL = {
        "MICROSOFT_GRAPH_CLIENT_ID": MS365_CLIENT_ID,
        "MICROSOFT_GRAPH_CLIENT_SECRET": MS365_CLIENT_SECRET,
        "MICROSOFT_GRAPH_TENANT_ID": MS365_TENANT_ID,
    }
else:
    # Fallback to standard SMTP backend (username/password) to avoid OAuth errors
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    # Use safe env readers so empty values don't override defaults
    EMAIL_HOST = env_str_safe("EMAIL_HOST", default="smtp.office365.com")
    EMAIL_PORT = env_int_safe("EMAIL_PORT", default=587)
    EMAIL_USE_TLS = env_bool_safe("EMAIL_USE_TLS", default=True)
    EMAIL_HOST_USER = env_str_safe("EMAIL_HOST_USER", default="")
    EMAIL_HOST_PASSWORD = env_str_safe("EMAIL_HOST_PASSWORD", default="")

# Optional: use console backend in dev if desired
# if DEVELOPMENT_MODE and env.bool("EMAIL_USE_CONSOLE", default=False):
#     EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# initialized environ
env = Env()
env.read_env(os.path.join(BASE_DIR, ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Always load SECRET_KEY from environment variables, never hardcode it
SECRET_KEY = env.str("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
# DEBUG = os.getenv("DEBUG", "False") == "True"
DEBUG = env.bool("DEBUG", default=True)


#
# ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
# ALLOWED_HOSTS = []
ALLOWED_HOSTS = env.list(
    "ALLOWED_HOSTS", default=["127.0.0.1", "localhost", "testserver"]
)

# CSRF Settings
if DEVELOPMENT_MODE:
    CSRF_TRUSTED_ORIGINS = ["http://127.0.0.1:8000", "http://localhost:8000"]
else:
    CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])


# CSRF_TRUSTED_ORIGINS = env.list(
#     "CSRF_TRUSTED_ORIGINS",
#     default=[
#         "http://127.0.0.1:8000",
#         "http://localhost:8000",
#         "https://127.0.0.1:8000",
#         "https://localhost:8000",
#         "https://clownfish-app-a9wz7.ondigitalocean.app",
#         "https://nexus.cd",
#     ],
# )

USE_SPACES = env.bool("USE_SPACES", default=False)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    # Added Libraries
    "rest_framework",
    "rest_framework_gis",
    "storages",
    "rosetta",
    # 'django_crontab',
    "django_celery_beat",
    "django_extensions",
    "compressor",
    # Internal
    "main",
    "backoffice",
    "api",
    "tech",
    "user",
    "subscriptions",
    "sales",
    "orders",
    "stock",
    "customers",
    "client_app",
    "dashboard_bi",
    "kyc_management",
    "app_settings",
    "feedbacks",
    "geo_regions",
    "billing_management",
    "site_survey",
    "ticketing",
    "promotions",
]

# In test/CI environments, disable django-compressor to avoid unnecessary
# static pipeline configuration and related startup errors.
if env.bool("TESTING", default=False):
    INSTALLED_APPS = [app for app in INSTALLED_APPS if app != "compressor"]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Multilingual
    "django.middleware.locale.LocaleMiddleware",
]

# Custom App Auth model
AUTH_USER_MODEL = "main.User"

ROOT_URLCONF = "nexus_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "client_app.context_processors.kyc_status_context",
            ],
            # Auto-load custom template tags across all templates
            "builtins": [
                "main.templatetags.form_extras",
            ],
        },
    },
]

WSGI_APPLICATION = "nexus_backend.wsgi.application"

FLEXPAY_MERCHANT_ID = env.str("FLEXPAY_MERCHANT_ID")
FLEXPAY_API_KEY = env.str("FLEXPAY_API_KEY")
FLEXPAY_MOBILE_URL = env.str("FLEXPAY_MOBILE_URL")
FLEXPAY_CHECK_URL = env.str("FLEXPAY_CHECK_URL")
FLEXPAY_CARD_URL = env.str("FLEXPAY_CARD_URL")


# SendGrid
SENDGRID_API_KEY = env.str("SENDGRID_API_KEY", default="")
EMAIL_HOST_FROM = "no-reply@yourdomain.com"

# Email configuration for notifications
if "DEFAULT_FROM_EMAIL" not in globals():
    DEFAULT_FROM_EMAIL = env.str("DEFAULT_FROM_EMAIL", default="nexus@example.com")
SUPPORT_EMAIL = env.str("SUPPORT_EMAIL", default="support@nexus.com")
SUPPORT_PHONE = env.str("SUPPORT_PHONE", default="+33 1 23 45 67 89")
ADMIN_NOTIFICATION_EMAILS = env.list("ADMIN_NOTIFICATION_EMAILS", default=[])
SITE_URL = env.str("SITE_URL", default="http://localhost:8000")

# Email backend configuration (overridden above by Anymail Microsoft Graph)
# Kept for legacy reference; not used when ANYMAIL backend is enabled.
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = env.str("EMAIL_HOST", default="smtp.office365.com")
# EMAIL_PORT = env.int("EMAIL_PORT", default=587)
# EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
# EMAIL_HOST_USER = env.str("EMAIL_HOST_USER", default="")
# EMAIL_HOST_PASSWORD = env.str("EMAIL_HOST_PASSWORD", default="")

# Twilio
TWILIO_ACCOUNT_SID = env.str("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = env.str("TWILIO_AUTH_TOKEN")
TWILIO_API_SECRET = env.str("TWILIO_API_SECRET")
TWILIO_PHONE_NUMBER = env.str("TWILIO_PHONE_NUMBER")

# Google MAPS API
GOOGLE_MAPS_API_KEY = env.str("GOOGLE_MAPS_API_KEY")

# Django GIS
# if DEVELOPMENT_MODE:
#     GDAL_LIBRARY_PATH = os.environ.get("GDAL_LIBRARY_PATH")
#     GEOS_LIBRARY_PATH = os.environ.get("GEOS_LIBRARY_PATH")
# else:
#     import ctypes.util
#
#     GDAL_LIBRARY_PATH = os.getenv("GDAL_LIBRARY_PATH") or ctypes.util.find_library("gdal")
#     GEOS_LIBRARY_PATH = os.getenv("GEOS_LIBRARY_PATH") or ctypes.util.find_library("geos_c")
#     os.environ.setdefault("PROJ_LIB", os.getenv("PROJ_LIB", "/usr/share/proj"))
DO_APT_LIB = "/layers/digitalocean_apt/apt/usr/lib/x86_64-linux-gnu"
DO_APT_SHARE = "/layers/digitalocean_apt/apt/usr/share"


def _pick_lib(basename: str, search_dir: str) -> str | None:
    """Return an absolute path to lib (non-versioned or versioned), if present."""
    direct = join(search_dir, basename)
    if exists(direct):
        return direct
    matches = sorted(glob.glob(join(search_dir, basename + "*")))
    return matches[0] if matches else None


def _default_proj_lib() -> str:
    p = join(DO_APT_SHARE, "proj")
    return p if isdir(p) else "/usr/share/proj"


def _default_gdal_data() -> str:
    p = join(DO_APT_SHARE, "gdal")
    return p if isdir(p) else "/usr/share/gdal"


if DEVELOPMENT_MODE:
    # Local/dev: use env if set, else let ctypes find system libs
    GDAL_LIBRARY_PATH = os.getenv("GDAL_LIBRARY_PATH") or ctypes.util.find_library(
        "gdal"
    )
    GEOS_LIBRARY_PATH = os.getenv("GEOS_LIBRARY_PATH") or ctypes.util.find_library(
        "geos_c"
    )
    os.environ.setdefault("PROJ_LIB", os.getenv("PROJ_LIB", _default_proj_lib()))
    os.environ.setdefault("GDAL_DATA", os.getenv("GDAL_DATA", _default_gdal_data()))
else:
    # App Platform: prefer env; else auto-pick from the DO apt layer; else ctypes fallback
    gdal = os.getenv("GDAL_LIBRARY_PATH")
    geos = os.getenv("GEOS_LIBRARY_PATH")

    if not gdal and isdir(DO_APT_LIB):
        gdal = _pick_lib("libgdal.so", DO_APT_LIB)
    if not geos and isdir(DO_APT_LIB):
        geos = _pick_lib("libgeos_c.so", DO_APT_LIB)

    GDAL_LIBRARY_PATH = gdal or ctypes.util.find_library("gdal")
    GEOS_LIBRARY_PATH = geos or ctypes.util.find_library("geos_c")

    # Data directories
    os.environ.setdefault("PROJ_LIB", os.getenv("PROJ_LIB", _default_proj_lib()))
    os.environ.setdefault("GDAL_DATA", os.getenv("GDAL_DATA", _default_gdal_data()))

    # Ensure the dynamic linker sees the DO apt layer
    if isdir(DO_APT_LIB):
        os.environ["LD_LIBRARY_PATH"] = (
            f'{DO_APT_LIB}:{os.getenv("LD_LIBRARY_PATH","")}'
        )


# Graceful GIS fallback for non-spatial backends in tests
# ------------------------------------------------------
# When running tests against a database backend that does not expose
# geo_db_type (e.g. SQLite or plain PostgreSQL), migrations for GIS
# fields would normally fail. We patch GeometryField.db_type to fall
# back to a simple textual column in that case so that the schema can
# still be created and non-spatial tests can run.
try:
    from django.contrib.gis.db.models.fields import GeometryField

    _original_geometry_db_type = GeometryField.db_type

    def _safe_geometry_db_type(self, connection):
        ops = getattr(connection, "ops", None)
        if not getattr(ops, "geo_db_type", None):
            return "text"
        return _original_geometry_db_type(self, connection)

    GeometryField.db_type = _safe_geometry_db_type  # type: ignore[assignment]
except Exception:
    # If GIS is not installed at all, don't break settings import.
    pass


import dj_database_url

# Database
DATABASES_URL = env.str("DATABASES_URL", None)

if env.bool("TESTING", default=False):
    # In CI/test environments we always provide DATABASE_URL; prefer it over
    # per-field DATABASE_* vars so configuration is centralized in the workflow.
    db_url = os.environ.get("DATABASE_URL")
    if db_url:
        cfg = dj_database_url.parse(db_url, conn_max_age=600)
        cfg["ENGINE"] = "django.contrib.gis.db.backends.postgis"
        DATABASES = {"default": cfg}
    else:
        # Fallback to a simple local Postgres setup for tests if DATABASE_URL
        # is not defined for some reason.
        DATABASES = {
            "default": {
                "ENGINE": "django.contrib.gis.db.backends.postgis",
                "NAME": "nexus_test",
                "USER": "postgres",
                "PASSWORD": env.str("DATABASE_PASSWORD", default="postgres"),
                "HOST": "localhost",
                "PORT": "5432",
            }
        }
elif DEVELOPMENT_MODE is True:
    DATABASES = {
        "default": {
            "ENGINE": "django.contrib.gis.db.backends.postgis",
            "NAME": "nexus_db",
            "USER": "postgres",
            "PASSWORD": env.str("DATABASE_PASSWORD"),
            "HOST": "localhost",
            "PORT": "5432",
            # No SSL for local
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.contrib.gis.db.backends.postgis",
            "NAME": env.str("DATABASE_NAME"),
            "USER": env.str("DATABASE_USER"),
            "PASSWORD": env.str("DATABASE_PASSWORD"),
            "HOST": env.str("DATABASE_HOST"),
            "PORT": env.str("DATABASE_PORT"),
            # "OPTIONS": {
            #     "sslmode": "require",  # Renforcer SSL
            # },
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Password Hashing
# https://docs.djangoproject.com/en/5.2/topics/auth/passwords/#using-argon2-with-django
# Argon2 is the winner of the 2015 Password Hashing Competition and is the most secure option
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",  # Most secure (requires argon2-cffi)
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",  # Django default, good fallback
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",  # Legacy support
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",  # Alternative (requires bcrypt)
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ("en", "English"),
    ("fr", "Français"),
]

LOCALE_PATHS = [
    BASE_DIR / "locale",
]

# === ROSETTA CONFIGURATION ===
# Django-rosetta configuration for translation management
# Treat English as the base/source language
ROSETTA_SHOW_AT_ADMIN_PANEL = True
ROSETTA_REQUIRES_AUTH = True

# English is the source language - don't show it in Rosetta interface
# Only show languages that need translation (fr, etc.)
ROSETTA_EXCLUDED_APPLICATIONS = [
    "django",  # Exclude Django's own translations
    "admin",  # Exclude admin translations
]

# Auto-reload translations in development
ROSETTA_AUTO_RELOAD = DEBUG

# Storage backend for Rosetta files (optional - uses default file storage)
# ROSETTA_STORAGE_CLASS = 'django.core.files.storage.FileSystemStorage'

# Enable auto-compilation of .po files to .mo files
ROSETTA_POFILE_WRAP_WIDTH = 0  # No line wrapping

# Language selection for Rosetta interface
# This ensures English appears as the reference language
ROSETTA_LANGUAGE_GROUPS = {
    "main": ["fr"],  # Only show French for translation
    # English is implied as the source - no need to translate EN to EN
}

# Show original string (msgid) prominently as the English source
ROSETTA_SHOW_TRANSLATION_HELP = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# Use S3 for static files

if USE_SPACES:
    # DigitalOcean Spaces Credentials
    # AWS_S3_ADDRESSING_STYLE = "virtual"
    AWS_DEFAULT_ACL = "public-read"
    AWS_ACCESS_KEY_ID = env.str("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = env.str("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = env.str(
        "AWS_STORAGE_BUCKET_NAME", default="nexustelecoms"
    )
    AWS_S3_REGION_NAME = "fra1"
    # AWS_S3_ENDPOINT_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.{AWS_S3_REGION_NAME}.digitaloceanspaces.com'
    AWS_S3_ENDPOINT_URL = f"https://{AWS_S3_REGION_NAME}.digitaloceanspaces.com"
    AWS_S3_CUSTOM_DOMAIN = (
        f"{AWS_STORAGE_BUCKET_NAME}.{AWS_S3_REGION_NAME}.cdn.digitaloceanspaces.com"
    )

    # Common S3 Settings
    AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "max-age=86400"}

    # Static Files Configuration
    AWS_LOCATION = "static"
    # STATIC_URL = f'{AWS_S3_ENDPOINT_URL}/{AWS_LOCATION}/'
    STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/"

    # Media Files Configuration (private or public)
    PRIVATE_MEDIA_LOCATION = "private"
    PRIVATE_FILE_STORAGE = "nexus_backend.storage_backends.PrivateMediaStorage"
    DEFAULT_FILE_STORAGE = "nexus_backend.storage_backends.PrivateMediaStorage"

else:
    # Local Development Static & Media Settings
    STATIC_URL = "/static/"
    STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

    MEDIA_URL = "/media/"
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
    DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"


STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")  # Optional fallback

# Django Compressor settings
COMPRESS_ROOT = STATIC_ROOT
COMPRESS_ENABLED = True
# In CI / test environments, ensure COMPRESS_URL is never None to keep
# django-compressor happy even if STATIC_URL is not fully configured yet.
if env.bool("TESTING", default=False):
    COMPRESS_URL = "/static/"
else:
    COMPRESS_URL = STATIC_URL
COMPRESS_STORAGE = "compressor.storage.CompressorFileStorage"
# Enable offline compression by default in production, disable in development.
# Can be overridden via env var COMPRESS_OFFLINE.
COMPRESS_OFFLINE = env.bool("COMPRESS_OFFLINE", default=not DEVELOPMENT_MODE)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "feedback_mutation": env.str("FEEDBACK_CLIENT_RATE_LIMIT", default="10/min"),
        "feedback_attachment": env.str(
            "FEEDBACK_ATTACHMENT_RATE_LIMIT", default="10/min"
        ),
        "feedback_staff_action": env.str("FEEDBACK_STAFF_RATE_LIMIT", default="30/min"),
    },
}

FEEDBACK_SETTINGS = {
    "DEFAULT_EDIT_WINDOW_DAYS": env.int("FEEDBACK_EDIT_WINDOW_DAYS", default=7),
    "EDIT_WINDOW_BASE": env.str(
        "FEEDBACK_EDIT_WINDOW_BASE", default="completion"
    ),  # completion | submission
    "ENABLE_STAFF_REPLY_EMAIL": env.bool(
        "FEEDBACK_ENABLE_STAFF_REPLY_EMAIL", default=False
    ),
    "ENABLE_LOCK_EMAIL": env.bool("FEEDBACK_ENABLE_LOCK_EMAIL", default=False),
    "REMINDER_DAYS_AFTER_JOB": env.int("FEEDBACK_REMINDER_DAYS_AFTER_JOB", default=3),
    "MAX_ATTACHMENT_SIZE": env.int(
        "FEEDBACK_MAX_ATTACHMENT_SIZE", default=5 * 1024 * 1024
    ),
    "ALLOWED_ATTACHMENT_TYPES": env.list(
        "FEEDBACK_ALLOWED_ATTACHMENT_TYPES",
        default=[
            "image/jpeg",
            "image/png",
            "application/pdf",
        ],
    ),
    "SANITIZE_ALLOWED_TAGS": [
        "p",
        "br",
        "strong",
        "em",
        "ul",
        "ol",
        "li",
        "a",
        "code",
    ],
    "SANITIZE_ALLOWED_ATTRIBUTES": {"a": ["href", "title", "rel"]},
    "NOTIFY_RECIPIENTS": env.list(
        "FEEDBACK_NOTIFICATION_RECIPIENTS", default=ADMIN_NOTIFICATION_EMAILS
    ),
}


if DEVELOPMENT_MODE:
    # Celery basics
    VALKEY_URL = env.str("CELERY_BROKER_URL")
else:
    VALKEY_URL = env.str("VALKEY_URL")
    # Minimal (no CA verification – quick fix):
    BROKER_USE_SSL = {"ssl_cert_reqs": ssl.CERT_NONE}
    RESULT_BACKEND_TRANSPORT_OPTIONS = {"ssl_cert_reqs": ssl.CERT_NONE}
    CELERY_BROKER_URL = VALKEY_URL
    CELERY_RESULT_BACKEND = VALKEY_URL
CELERY_TIMEZONE = TIME_ZONE  # reuse Django TZ
CELERY_ENABLE_UTC = False
# Belt-and-suspenders: also list imports here
CELERY_IMPORTS = ("nexus_backend.celery_tasks.tasks",)


# Test settings
if "test" in os.sys.argv or "pytest" in os.sys.argv[0]:
    # Allow opting into running tests against a real PostGIS test database by
    # setting USE_POSTGIS_TESTS=1 in the environment. When that flag is present
    # we avoid forcing an in-memory SQLite database (which is incompatible with
    # GeoDjango fields). By default (no flag) we use SQLite for fast, isolated
    # unit tests.
    use_postgis_tests = os.getenv("USE_POSTGIS_TESTS")

    if not use_postgis_tests:
        # Use in-memory SQLite for tests (fast path when PostGIS isn't needed)
        DATABASES["default"] = {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:",
        }

    # Disable migrations for faster tests (kept for both SQLite and PostGIS runs)
    class DisableMigrations:
        def __contains__(self, item):
            return True

        def __getitem__(self, item):
            return None

    MIGRATION_MODULES = DisableMigrations()

    # Use console email backend for tests
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

    # EMAIL_BACKEND = "anymail.backends.microsoft_graph.EmailBackend"
    #
    # ANYMAIL = {
    #     "MICROSOFT_GRAPH_CLIENT_ID": os.getenv("MS365_CLIENT_ID"),
    #     "MICROSOFT_GRAPH_CLIENT_SECRET": os.getenv("MS365_CLIENT_SECRET"),
    #     "MICROSOFT_GRAPH_TENANT_ID": os.getenv("MS365_TENANT_ID"),
    #     # If in a sovereign cloud, set:
    #     # "MICROSOFT_GRAPH_AUTHORITY": "https://login.microsoftonline.us/<tenant>",
    #     # "MICROSOFT_GRAPH_API_ENDPOINT": "https://graph.microsoft.us/v1.0",
    # }
    #
    # DEFAULT_FROM_EMAIL = "Nexus <no-reply@nexus.cd>"

    # Disable Celery tasks during tests
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True

    # Disable Sentry during tests
    import sentry_sdk

    sentry_sdk.init(dsn=None)

    # Use secure but faster password hashing for tests
    # PBKDF2 is secure and faster than Argon2 for test performance
    PASSWORD_HASHERS = [
        "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    ]

    # Disable logging during tests
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": True,
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
            },
        },
        "loggers": {
            "django": {
                "handlers": ["console"],
                "level": "WARNING",
            },
        },
    }

else:
    # Error bugs Logs
    import sentry_sdk

    sentry_sdk.init(
        dsn="https://98264f53e268e1e6787787a8e2b5af78@o554823.ingest.us.sentry.io/4509830070468608",
        # Add data like request headers and IP for users;
        # see https://docs.sentry.io/platforms/python/data-management/data-collected/ for more info
        send_default_pii=True,
    )

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": "debug.log",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "user.views": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "user.auth": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "client_app.views": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}
